# Title and subheading for your site. Used on the home page and in page
# titles.
#
title: Marshall Yount
subtitle: From the power plug to the </html>

# You should really specify your content's author when generating an
# Atom feed. Specify at least one of name, uri or email, and Nesta will
# include it in your feed. See the Atom spec for more info:
#
# http://www.atomenabled.org/developers/syndication/atom-format-spec.php#element.feed
#
author:
  name: Marshall Yount
  uri: http://yountlabs.com
  email: marshall.yount@gmail.com

# You can stick with the default look and feel, or use a theme. Themes are
# easy to create or install, and live inside the themes directory. You
# can also use scripts/theme to install them.
#
theme: wynn

# If you want to use the Disqus service (http://disqus.com) to display
# comments on your site, register a Disqus account and then specify your
# site's short name here. A comment form will automatically be added to
# the bottom of your pages.
#
disqus_short_name: yountlabs

# cache
#     Set it to true if you'd like Nesta to cache your pages in ./public.
#     Useful if you're deploying Nesta with a proxy server such as Nginx,
#     but not in the least bit helpful if your pages are dynamic, or you're
#     deploying Nesta to Heroku.
#
cache: false

# content
#     The root directory where nesta will look for your article files.
#     Should contain "pages" and "attachments" subdirectories that contain
#     your actual content and the (optional) menu.txt file that links to your
#     main category pages.
#
content: content

# google_analytics_code
#     Set this if you want Google Analytics to track traffic on your site.
#     Probably best not to set a default value, but to set it in production.
#
#     The production settings are used if you're deploying to Heroku, so
#     scroll down a bit to set it in production even if you're not deploying
#     to your own server.
#
# google_analytics_code: "UA-???????-?"

# expires
#     The amount of time each page can be cached for by the client. If your
#     pages changes very often, set this to a small value. If on the other hand
#     your pages are mostly static, set it to a large value. Within the time you
#     put, a browser that has a copy of the file in its cache might choose not
#     to requery your website for the latest version. Can be overriden in
#     individual pages. In seconds.
#     Default: 0

expires: 3600

# expires_type
#     Whether or not proxies can cache the pages we serve. If set to public,
#     both proxies between the browser and the web server and the browser itself
#     can cache the pages. If set to private, only the client's browser can.
#     In practice, if the pages are modified depending on who requests
#     them, you should set this to private. Otherwise if all clients get the
#     same page (usually the case, particularly on nesta websites), set it to
#     public.
#     Default: public

expires_type: public

production:
  cache: false
  content: content
  google_analytics_code: "UA-11252985-1"
